### ISSUE TITLE
can not get snapcraft working

### ISSUE THREAD

**Issue by SgtScriptKiddy** [SgtScriptKiddy/go-github-stats#3]
With no CS degree, im dumb and need help, 

THANK YOU

**Comment by SgtScriptKiddy** [comment]
error: 
`
    Pulling github-stats 
    Cloning into '/build/github-stats/parts/github-stats/src'...
    package context: unrecognized import path "context" (import path does not begin with hostname)
    go get -t -d ./SgtScriptKiddy/github-stats/...
    Failed to run 'go get -t -d ./SgtScriptKiddy/github-stats/...' for 'github-stats': Exited with code 1.
    Verify that the part is using the correct parameters and try again.
    Build failed
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 269, in run
        self.pull()
      File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 221, in pull
        env=env)
      File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 103, in run_build_command
        return self.backend.run(args, cwd=cwd, env=full_env, **kwargs)
      File "/usr/lib/python2.7/dist-packages/lpbuildd/target/lxd.py", line 456, in run
        subprocess.check_call(cmd, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command '['lxc', 'exec', 'lp-xenial-i386', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_LOCAL_SOURCES=1', '--env', 'SNAPCRAFT_SETUP_CORE=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build_url": "https://snap-proxy.launchpad.net:3128', '--env', 'https_proxy=http://snap-proxy.launchpad.net:3128', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/github-stats && linux32 snapcraft pull']' returned non-zero exit status 2
    Revoking proxy token...
    RUN: /usr/share/launchpad-buildd/slavebin/in-target scan-for-processes --backend=lxd --series=xenial --arch=i386 SNAPBUILD-209395
    Scanning for processes to kill in build SNAPBUILD-209395
    RUN: /usr/share/launchpad-buildd/slavebin/in-target umount-chroot --backend=lxd --series=xenial --arch=i386 SNAPBUILD-209395
    Stopping target for build SNAPBUILD-209395
    /usr/lib/python2.7/dist-packages/pylxd/model.py:116: UserWarning: Attempted to set unknown attribute "description" on instance of "Container"
      key, self.__class__.__name__
    RUN: /usr/share/launchpad-buildd/slavebin/in-target remove-build --backend=lxd --series=xenial --arch=i386 SNAPBUILD-209395
`
